### ISSUE TITLE
Gov Delivery moved image need to update so images shows

### ISSUE THREAD

**Issue by vwolfley** [AZMAG/map-LandUse#1]
New link code - https://public.govdelivery.com/assets/required-139b548414c88442cfc0772133ef4b70da67b21046b31a86cea9bf6a0dc7c9d3.gif

**Comment by Jfairfield1** [comment]
Subscribe functionality is not currently in this viewer

**Comment by Jfairfield1** [comment]
Added Subscribe feature and updated gov delivery image.
